routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'prevent-back-history'], function () {

    Auth::routes();

    Route::get('/', 'WebController@index')->name('shop');

    Route::get('filter/{id}', 'WebController@filter')->name('filter');

    Route::get('new', 'WebController@newProducts')->name('newProducts');

    Route::get('bestseller', 'WebController@bestseller')->name('bestseller');

    Route::get('search', 'WebController@search')->name('search');

    Route::get('detail-product/{id}', 'WebController@detailProduct')->name('detailProduct');

    Route::get('add-to-cart/{id}', 'CartController@addToCart')->name('addToCart');

    Route::resource('bills', 'BillsController');

    Route::get('sendMail', 'MailController@email')->name('send');

    Route::get('users/{id}/edit', 'WebController@editUsers')->name('account');

    Route::post('users/{id}', 'WebController@updateUsers')->name('change');

    Route::group(['middleware' => 'sessionCart'], function () {

        Route::get('cart', 'CartController@index')->name('cart');

    });

    Route::post('checkout', 'CartController@checkout')->name('checkout');

//    Route::get('updateItems/{id}', 'CartController@updateItems')->name('updateItems');

    Route::get('delete-item/{id}', 'CartController@deleteItems')->name('deleteItems');


    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('/admin/categories', 'CategoriesController');

        Route::resource('/admin/products', 'ProductsController');

        Route::resource('/admin/order', 'OrderController');

        Route::resource('/admin/users', 'UserController');

        Route::get('/admin', 'HomeController@index')->name('admin');
    });
});

app/Products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $fillable = [
        'id', 'name', 'categories_id', 'price', 'quantity', 'description', 'image', 'promotion_price', 'sold'
    ];

    public function categories()
    {
        return $this->belongsTo('App\Categories');
    }

    public function billDetails()
    {
        return $this->hasMany('App\BillDetails', 'products_id', 'id');
    }

    public $timestamps = false;
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use App\Http\Requests\ProductsRequest;
use App\Http\Requests\UpdateProductsRequest;
use App\Products;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ProductsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $categories = Categories::all();
        $products = Products::paginate(5);
        return view('admin.products.products', compact('products', 'categories'));
    }

    public function create()
    {
        $categories = Categories::all();
        $products = Products::all();
        return view('admin.products.add', compact('categories', 'products'));
    }

    public function store(ProductsRequest $request)
    {
        $products = new Products();
        $products->name = $request->name;
        $products->categories_id = $request->categories_id;
        $products->description = $request->description;
        $products->price = $request->price;
        $products->quantity = $request->quantity;
        $products->promotion_price = $request->promotion_price;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $getImage = Str::random(5) . '_' . $image->getClientOriginalName();
            $destinationPath = public_path('/images');
            $image->move($destinationPath, $getImage);
            $products->image = $getImage;
        } else {
            $products->image = '';
        }
        $products->save();

        return redirect()->route('products.index')->with('success', 'Product created successfully.');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $products = Products::findOrFail($id);
        $categories = Categories::all();
        return view('admin.products.edit', compact('products', 'categories'));
    }

    public function update(UpdateProductsRequest $request, $id)
    {
        $products = Products::findOrFail($id);
        $products->name = $request->name;
        $products->categories_id = $request->categories_id;
        $products->price = $request->price;
        $products->description = $request->description;
        $products->quantity = $request->quantity;
        $products->promotion_price = $request->promotion_price;
        $products->status = $request->status;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $getImage = Str::random(5) . '_' . $image->getClientOriginalName();
            $destinationPath = public_path('/images');
            $image->move($destinationPath, $getImage);
            unlink('images/' . $products->image);
            $products->image = $getImage;
        } else {
            $request->image = $products->image;
        }

        $products->save();
        return redirect()->route('products.index')->with('success', 'Product updated successfully');
    }

    public function destroy($id)
    {
        $products = Products::findOrFail($id);
        $products->delete();
        unlink('images/' . $products->image);
        return redirect()->route('products.index')->with('success', 'Product deleted successfully');
    }
}

resources/views/admin/products/add.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @if ($errors->any())

                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <strong>ADD</strong> Product
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">New Product Name</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="name" placeholder="New Product Name"
                                               class="form-control" value="{{ old('name') }}">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Category</label>
                                    </div>

                                    <div class="col-12 col-md-9">
                                        <select name="categories_id" class="form-control">
                                            @foreach($categories as $category)
                                                <option value='{{ $category->id }}'>{{$category->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Price</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input id="price" type="text" class="form-control" name="price"
                                               placeholder="Price" value="{{ old('price') }}">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Promotion Price</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input id="promotion_price" type="text" class="form-control"
                                               name="promotion_price"
                                               placeholder="Promotion Price" value="{{ old('promotion_price') }}">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Quantity</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input id="quantity" type="text" class="form-control" name="quantity"
                                               placeholder="Quantity" value="{{ old('quantity') }}">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Description</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input id="description" type="text" class="form-control" name="description"
                                               placeholder="Description" value="{{ old('description') }}">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Product Image</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input id="image" type="file" class="form-control" name="image">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="zmdi zmdi-check"></i> Create
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @if ($errors->any())

                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{route('products.update',$products->id)}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="card">
                        <div class="card-header">
                            <strong>Edit</strong> {{$products->name}}
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Product Name</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="name"
                                               placeholder="Category Name"
                                               class="form-control" value="{{$products->name}}">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Category</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <select name="categories_id" class="form-control">
                                            @foreach($categories as $category)
                                                <option
                                                    @if($products->categories_id == $category->id)
                                                    {{'selected'}}
                                                    @endif
                                                    value='{{$category->id }}'>{{$category->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Price</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="price"
                                               placeholder="Price"
                                               class="form-control" value="{{$products->price}}">
                                    </div>
                                </div>

                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Promotion Price</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="promotion_price"
                                               placeholder="Promotion Price"
                                               class="form-control" value="{{$products->promotion_price}}">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Quantity</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="quantity"
                                               placeholder="Quantity"
                                               class="form-control" value="{{$products->quantity}}">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Description</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="description"
                                               placeholder="Description"
                                               class="form-control" value="{{$products->description}}">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Status</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <select name="status" class="form-control">
                                            <option @if($products->status == 1)
                                                    {{'selected'}}
                                                    @endif value='1'> New
                                            </option>
                                            <option @if($products->status == 0)
                                                    {{'selected'}}
                                                    @endif value='0'>Old
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Product Image</label>
                                    </div>
                                    <div class="col-md-6">
                                        <img src="images/{{$products->image}}">
                                        <input id="image" type="file" class="form-control" name="image">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="zmdi zmdi-check"></i> Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/products/products.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @if ($errors->any())

                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="title-1">all Products</h2>
                        <div class="table-data__tool">
                            <div class="table-data__tool-right">
                                <a class="au-btn au-btn-icon au-btn--green au-btn--small"
                                   href="{{route('products.create')}}">
                                    <i class="zmdi zmdi-plus"></i>ADD product
                                </a>
                            </div>
                        </div>
                        <div class="table-responsive table-responsive-data2">
                            <table class="table table-data2">
                                <thead>
                                <tr>
                                    <th>name</th>
                                    <th>category</th>
                                    <th>price</th>
                                    <th>promotion price</th>
                                    <th>quantity</th>
                                    <th>image</th>
                                    <th></th>
                                </tr>
                                </thead>
                                @foreach($products as $product)
                                    <tbody>
                                    <tr class="tr-shadow">
                                        <td class="desc">{{$product->name}}</td>
                                        <td class="desc">{{$product->categories['name']}}</td>
                                        <td class="desc">${{number_format($product->price)}}</td>
                                        <td class="desc">${{number_format($product->promotion_price)}}</td>
                                        <td class="desc">{{$product->quantity}}</td>
                                        <td style="padding: 0">
                                            <img width="100px" src="images/{{$product->image }}">
                                        </td>
                                        <td>
                                            <div class="table-data-feature">
                                                <a class="item" href="{{ route('products.edit',$product->id) }}"
                                                   data-placement="top"
                                                   title="Edit">
                                                    <i class="zmdi zmdi-edit"></i>
                                                </a>
                                                <form action="{{route('products.destroy', $product->id)}}"
                                                      onclick="return window.confirm('Are you sure ?');" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="item" data-placement="top"
                                                            title="Delete"><i class="zmdi zmdi-delete"></i>
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr class="spacer"></tr>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                    {!! $products->links() !!}
                    <!-- END DATA TABLE -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection