routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'prevent-back-history'], function () {

    Auth::routes();

    Route::get('/', 'WebController@index')->name('shop');

    Route::get('filter/{id}', 'WebController@filter')->name('filter');

    Route::get('new', 'WebController@newProducts')->name('newProducts');

    Route::get('bestseller', 'WebController@bestseller')->name('bestseller');

    Route::get('search', 'WebController@search')->name('search');

    Route::get('detail-product/{id}', 'WebController@detailProduct')->name('detailProduct');

    Route::get('add-to-cart/{id}', 'CartController@addToCart')->name('addToCart');

    Route::resource('bills', 'BillsController');

    Route::get('sendMail', 'MailController@email')->name('send');

    Route::get('users/{id}/edit', 'WebController@editUsers')->name('account');

    Route::post('users/{id}', 'WebController@updateUsers')->name('change');

    Route::group(['middleware' => 'sessionCart'], function () {

        Route::get('cart', 'CartController@index')->name('cart');

    });

    Route::post('checkout', 'CartController@checkout')->name('checkout');

//    Route::get('updateItems/{id}', 'CartController@updateItems')->name('updateItems');

    Route::get('delete-item/{id}', 'CartController@deleteItems')->name('deleteItems');


    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('/admin/categories', 'CategoriesController');

        Route::resource('/admin/products', 'ProductsController');

        Route::resource('/admin/order', 'OrderController');

        Route::resource('/admin/users', 'UserController');

        Route::get('/admin', 'HomeController@index')->name('admin');
    });
});

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use App\Http\Requests\CategoriesRequest;
use App\Products;


class CategoriesController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $categories = Categories::paginate(5);
        return view('admin.categories.categories', compact('categories'));
    }

    public function create()
    {
        return view('admin.categories.add');
    }

    public function store(CategoriesRequest $request)
    {

        $categories = new Categories();
        $categories->name = $request->name;
        $categories->save();
        return redirect()->route('categories.index')->with('success', 'Category created successfully.');
    }

    public function show($id)
    {
        $products = Products::where('categories_id', '=', $id)->paginate(5);
        return view('admin.products.products', compact('products'));
    }

    public function edit($id)
    {
        $categories = Categories::findOrFail($id);
        return view('admin.categories.edit', compact('categories'));
    }

    public function update(CategoriesRequest $request, $id)
    {
        $categories = Categories::find($id);
        $categories->name = $request->name;
        $categories->save();
        return redirect()->route('categories.index')->with('success', 'Category updated successfully');
    }

    public function destroy($id)
    {
        $categories = Categories::findOrFail($id);
        $categories->delete();
        $products = Products::where('categories_id', '=', $id);
        $products->delete();
        return redirect()->route('categories.index')->with('success', 'Category deleted successfully');
    }
}

resources/views/admin/categories/add.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{ route('categories.store') }}" method="POST">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <strong>ADD</strong> Category
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">New Category Name</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="name" placeholder="New Category Name"
                                               value="{{ old('name') }}"class="form-control">
                                    </div>
                                </div>

                            </form>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="zmdi zmdi-check"></i> Create
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/categories.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="title-1">all category</h2>
                        <div class="table-data__tool">
                            <div class="table-data__tool-right">
                                <a class="au-btn au-btn-icon au-btn--green au-btn--small"
                                   href="{{ route('categories.create')}}">
                                    <i class=" zmdi zmdi-plus"></i>ADD category
                                </a>
                            </div>
                        </div>
                        <div class="table-responsive table-responsive-data2">
                            <table class="table table-data2">
                                <thead>
                                <tr>
                                    <th>name</th>
                                    <th></th>
                                </tr>
                                </thead>
                                @foreach($categories as $category)
                                    <tbody>
                                    <tr class="tr-shadow">
                                        <td class="desc"><a
                                                href="{{route('categories.show',$category->id)}}">{{$category->name}}</a>
                                        </td>
                                        <td>
                                            <div class="table-data-feature">
                                                <a class="item" href="{{ route('categories.edit',$category->id) }}"
                                                   data-placement="top"
                                                   title="Edit">
                                                    <i class="zmdi zmdi-edit"></i>
                                                </a>
                                                <form action="{{ route('categories.destroy', $category->id)}}"
                                                      method="post" onclick="return window.confirm('Are you sure?');">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit"  class="item" data-placement="top"
                                                            title="Delete"><i class="zmdi zmdi-delete"></i>
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr class="spacer"></tr>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                    {!! $categories->links() !!}
                    <!-- END DATA TABLE -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{route('categories.update',$categories->id)}}" method="POST">
                    @csrf
                    @method('PATCH')
                    <div class="card">
                        <div class="card-header">
                            <strong>Edit</strong> {{$categories->name}}
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Category Name</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="name"
                                               placeholder="Category Name"
                                               class="form-control" value="{{$categories->name}}">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="zmdi zmdi-check"></i> Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection