routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'prevent-back-history'], function () {

    Auth::routes();

    Route::get('/', 'WebController@index')->name('shop');

    Route::get('filter/{id}', 'WebController@filter')->name('filter');

    Route::get('new', 'WebController@newProducts')->name('newProducts');

    Route::get('bestseller', 'WebController@bestseller')->name('bestseller');

    Route::get('search', 'WebController@search')->name('search');

    Route::get('detail-product/{id}', 'WebController@detailProduct')->name('detailProduct');

    Route::get('add-to-cart/{id}', 'CartController@addToCart')->name('addToCart');

    Route::resource('bills', 'BillsController');

    Route::get('sendMail', 'MailController@email')->name('send');

    Route::get('users/{id}/edit', 'WebController@editUsers')->name('account');

    Route::post('users/{id}', 'WebController@updateUsers')->name('change');

    Route::group(['middleware' => 'sessionCart'], function () {

        Route::get('cart', 'CartController@index')->name('cart');

    });

    Route::post('checkout', 'CartController@checkout')->name('checkout');

//    Route::get('updateItems/{id}', 'CartController@updateItems')->name('updateItems');

    Route::get('delete-item/{id}', 'CartController@deleteItems')->name('deleteItems');


    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('/admin/categories', 'CategoriesController');

        Route::resource('/admin/products', 'ProductsController');

        Route::resource('/admin/order', 'OrderController');

        Route::resource('/admin/users', 'UserController');

        Route::get('/admin', 'HomeController@index')->name('admin');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'admin', 'address','phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public $timestamps = false;

    public function bills()
    {
        return $this->hasMany('App\Bills', 'user_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UsersRequest;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $users = User::paginate(5);
        return view('admin.user.user', compact('users'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $users = User::findOrFail($id);
        return view('admin.user.edit', compact('users'));
    }

    public function update(UsersRequest $request, $id)
    {
        $users = User::findOrFail($id);
        $users->name = $request->name;
        $users->admin = $request->admin;
        $users->address = $request->address;
        $users->phone = $request->phone;
        $users->save();

        return redirect()->route('users.index')->with('success', 'User updated successfully');
    }

    public function destroy($id)
    {
        $users = User::findOrFail($id);
        $users->delete();

        return redirect()->route('users.index')->with('success', 'User deleted successfully');
    }
}

resources/views/admin/user/edit.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @if ($errors->any())

                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form action="{{route('users.update',$users->id)}}" method="POST">
                    @csrf
                    @method('PATCH')
                    <div class="card">
                        <div class="card-header">
                            <strong>Edit</strong> {{$users->name}}
                        </div>
                        <div class="card-body card-block">
                            <form action="" method="post" class="form-horizontal">
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">User Name</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="name"
                                               placeholder="User Name"
                                               class="form-control" value="{{$users->name}}">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">
                                            Authorization</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <select name="admin" class="form-control">

                                            <option @if($users->admin == 1)
                                                    {{'selected'}}
                                                    @endif value='1'> ADMIN
                                            </option>
                                            <option @if($users->admin == 0)
                                                    {{'selected'}}
                                                    @endif value='0'> Customer
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Address</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="address"
                                               placeholder="Address"
                                               class="form-control" value="{{$users->address}}">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="col col-md-3">
                                        <label class=" form-control-label">Phone</label>
                                    </div>
                                    <div class="col-12 col-md-9">
                                        <input type="text" name="phone"
                                               placeholder="Phone"
                                               class="form-control" value="{{$users->phone}}">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="zmdi zmdi-check"></i> Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/user.blade.php
@extends('layouts.admin.app')
@include('layouts.admin.headerDesktop')
@include('layouts.admin.headerMobile')
@include('layouts.admin.sidebar')
@section('content')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @if ($errors->any())

                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                {{ $error }}<br>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="title-1">all user</h2>
                        <div class="table-responsive table-responsive-data2">
                            <table class="table table-data2">
                                <thead>
                                <tr>
                                    <th>name</th>
                                    <th>email</th>
                                    <th>admin</th>
                                    <th>address</th>
                                    <th>phone</th>
                                    <th></th>
                                </tr>
                                </thead>
                                @foreach($users as $user)
                                    <tbody>
                                    <tr class="tr-shadow">
                                        <td class="desc">{{$user->name}}</td>
                                        <td>
                                            <span class="block-email">{{$user->email}}</span>
                                        </td>
                                        <td>@if($user->admin==1)
                                                ADMIN
                                            @else
                                                Customer
                                            @endif</td>
                                        <td>{{$user->address}}</td>
                                        <td>{{$user->phone}}</td>
                                        <td>
                                            <div class="table-data-feature">
                                                <a class="item" href="{{ route('users.edit',$user->id) }}"
                                                   data-placement="top"
                                                   title="Edit">
                                                    <i class="zmdi zmdi-edit"></i>
                                                </a>
                                                <form action="{{route('users.destroy', $user->id)}}"
                                                      onclick="return window.confirm('Are you sure?');" method="post">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="item" data-placement="top"
                                                            title="Delete"><i class="zmdi zmdi-delete"></i>
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr class="spacer"></tr>
                                    </tbody>
                                @endforeach
                            </table>
                        </div>
                    {!! $users->links() !!}
                    <!-- END DATA TABLE -->
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection